# Generated by Django 4.0.5 on 2022-06-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ratings'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.reviews'),
        ),
    ]
