# Generated by Django 4.0.5 on 2022-06-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_ratings_alter_item_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.item'),
            preserve_default=False,
        ),
    ]
